/** @type {import('tailwindcss').Config} */
export default {
  darkMode: 'class',
  content: [
    './index.html',
    './src/**/*.{js,ts,jsx,tsx}',
  ],
  theme: {
    extend: {
      colors: {
        'surface': '#fdf9f2',
        'surface-dim': '#dddad3',
        'surface-bright': '#fdf9f2',
        'surface-container-lowest': '#ffffff',
        'surface-container-low': '#f7f3ec',
        'surface-container': '#f1ede6',
        'surface-container-high': '#ece8e1',
        'surface-container-highest': '#e6e2db',
        'surface-variant': '#e6e2db',
        'surface-tint': '#605e5c',
        'background': '#fdf9f2',
        'on-surface': '#1c1c18',
        'on-surface-variant': '#4b4640',
        'on-background': '#1c1c18',
        'inverse-surface': '#31302c',
        'inverse-on-surface': '#f4f0e9',
        'inverse-primary': '#cac6c3',

        'outline': '#7c766f',
        'outline-variant': '#cdc5bd',

        'primary': '#000000',
        'on-primary': '#ffffff',
        'primary-container': '#1d1b1a',
        'on-primary-container': '#868381',
        'primary-fixed': '#e6e1df',
        'primary-fixed-dim': '#cac6c3',
        'on-primary-fixed': '#1d1b1a',
        'on-primary-fixed-variant': '#484645',

        'secondary': '#974813',
        'on-secondary': '#ffffff',
        'secondary-container': '#fd975d',
        'on-secondary-container': '#723000',
        'secondary-fixed': '#ffdbca',
        'secondary-fixed-dim': '#ffb68f',
        'on-secondary-fixed': '#331100',
        'on-secondary-fixed-variant': '#773200',

        'tertiary': '#000000',
        'on-tertiary': '#ffffff',
        'tertiary-container': '#2d1600',
        'on-tertiary-container': '#a77b51',
        'tertiary-fixed': '#ffdcbe',
        'tertiary-fixed-dim': '#f0bd8e',
        'on-tertiary-fixed': '#2d1600',
        'on-tertiary-fixed-variant': '#623f1b',

        'error': '#ba1a1a',
        'on-error': '#ffffff',
        'error-container': '#ffdad6',
        'on-error-container': '#93000a',

        // Legacy & spec alias mappings
        'ink': {
          DEFAULT: '#11100f',
          muted: '#57534e',
          subtle: '#8c827a',
          faint: '#d6d1ca',
        },
        'bronze': {
          DEFAULT: '#b45309',
          light: '#d97706',
          dark: '#78350f',
          faint: '#fef3c7',
        },
        'border': {
          DEFAULT: '#e7e2d8',
          subtle: '#f0ece3',
          dark: '#292524',
        },
      },
      borderRadius: {
        'DEFAULT': '0.25rem',
        'sm': '0.25rem',
        'md': '0.5rem',
        'lg': '0.5rem',
        'xl': '0.75rem',
        '2xl': '1rem',
        'full': '9999px',
      },
      spacing: {
        'space-xs': '0.25rem',
        'space-sm': '0.5rem',
        'space-md': '0.75rem',
        'space-lg': '1.25rem',
        'space-xl': '2rem',
        'margin': '1.25rem',
        'gutter': '1rem',
      },
      fontFamily: {
        serif: ['"Playfair Display"', 'Georgia', 'serif'],
        sans: ['"Manrope"', '"Inter"', 'sans-serif'],
        mono: ['"JetBrains Mono"', 'monospace'],
        'display-lg': ['"Playfair Display"', 'serif'],
        'display-lg-mobile': ['"Playfair Display"', 'serif'],
        'headline-lg': ['"Playfair Display"', 'serif'],
        'headline-md': ['"Playfair Display"', 'serif'],
        'headline-sm': ['"Playfair Display"', 'serif'],
        'numeral-section': ['"Playfair Display"', 'serif'],
        'title-lg': ['"Manrope"', 'sans-serif'],
        'title-md': ['"Manrope"', 'sans-serif'],
        'body-lg': ['"Manrope"', 'sans-serif'],
        'body-md': ['"Manrope"', 'sans-serif'],
        'body-sm': ['"Manrope"', 'sans-serif'],
        'label-md': ['"Manrope"', 'sans-serif'],
        'label-sm': ['"Manrope"', 'sans-serif'],
      },
      fontSize: {
        'display-lg': ['36px', { lineHeight: '44px', letterSpacing: '-0.02em', fontWeight: '600' }],
        'display-lg-mobile': ['28px', { lineHeight: '36px', letterSpacing: '-0.01em', fontWeight: '600' }],
        'headline-lg': ['24px', { lineHeight: '32px', letterSpacing: '-0.01em', fontWeight: '600' }],
        'headline-md': ['20px', { lineHeight: '28px', fontWeight: '500' }],
        'headline-sm': ['18px', { lineHeight: '24px', fontWeight: '500' }],
        'numeral-section': ['12px', { lineHeight: '16px', letterSpacing: '0.05em', fontWeight: '400' }],
        'title-lg': ['16px', { lineHeight: '22px', fontWeight: '600' }],
        'title-md': ['14px', { lineHeight: '20px', fontWeight: '600' }],
        'body-lg': ['16px', { lineHeight: '26px', fontWeight: '400' }],
        'body-md': ['14px', { lineHeight: '22px', fontWeight: '400' }],
        'body-sm': ['12px', { lineHeight: '18px', fontWeight: '400' }],
        'label-md': ['11px', { lineHeight: '16px', letterSpacing: '0.08em', fontWeight: '700' }],
        'label-sm': ['10px', { lineHeight: '14px', letterSpacing: '0.1em', fontWeight: '700' }],
      },
      letterSpacing: {
        editorial: '0.08em',
      },
    },
  },
  plugins: [],
};
